# -*- coding: utf-8 -*-
"""hughes3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1al6BPBzGMbKnvevSMPUjznsxXqiXOtUm
"""

# !/usr/bin/env python
# (c) hughes
# ----------------------------------------------------
#
# program created to show the marginal distribution of x and y using histograms

import random
import numpy as np
import matplotlib.pyplot as plt

# variables
n = 5000
mu = 10
sigma = 20
alpha = 5
beta = 2

# random from normal
r_norm = [random.gauss(mu, sigma) for i in range(n)]

# random from gamma
r_gamma = [np.random.gamma(alpha,beta) for i in range(n)]

# plot
figure, axis = plt.subplots(2,2)
axis[0][0].hist(r_norm, orientation = 'horizontal', color = 'r');
axis[1][0].hist(r_gamma, color = 'r');
axis[1][1].hist2d(r_norm, r_gamma, cmap = plt.cm.Reds);
figure.delaxes(axis[0][1]);
plt.show()

